apiVersion: v1
kind: Secret
metadata:
  name: inventory-secrets
  namespace: inventory
type: Opaque
stringData:
  connection-string: "Server=__REPLACE_WITH_SQL_SERVER__;Database=InventoryDb;User Id=__REPLACE_WITH_USER__;Password=__REPLACE_WITH_PASSWORD__;Encrypt=true;TrustServerCertificate=false;"
  jwt-secret: "__REPLACE_WITH_A_SECRET_OF_AT_LEAST_32_CHARACTERS__"

